version: '3'

services:
  # Define a Telegraf service
  telegraf:
    image: telegraf:1.11.0
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    links:
      - influxdb
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"

  # Define an InfluxDB service
  influxdb:
    image: influxdb:1.7.6
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"

  # Define a Chronograf service
  chronograf:
    image: chronograf:1.7.7
    environment:
      INFLUXDB_URL: http://influxdb:8086
      # KAPACITOR_URL: http://kapacitor:9092
    ports:
      - "8888:8888"
    links:
      - influxdb

  # Define a service for using the influx CLI tool.
  # docker-compose run influxdb-cli
  influxdb-cli:
    image: influxdb:1.7.6
    entrypoint:
      - influx
      - -host
      - influxdb
    links:
      - influxdb
